config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords',
    confirmations: 'users/confirmations',
    unlocks: 'users/unlocks'
  }
  resources :transfers

  
  get 'get_email' => 'home#get_email'  
  get 'my_account' => 'home#my_account'  
  root "home#index"
end

app/models/transfer.rb
class Transfer < ApplicationRecord

  has_one :user
  # encrypts :sender_account_number 
  # encrypts :receiver_account_number 
  encrypts :amount 

  validates :amount, presence: true, format: { with: /\A\d+(\.\d+)?\z/, message: "is incorrect" }, numericality: { greater_than: 0 }
  validates :sender_account_number, presence: true, format: { with: /\A\d{26}\z/, message: "is incorrect" }
  validates :receiver_account_number, presence: true, format: { with: /\A\d{26}\z/, message: "is incorrect" }
  validates :title, presence: true, format: { with: /\A[a-zA-ZąćęłńóśźżĄĆĘŁŃÓŚŹŻ\d\s,\-;!"?]+\z/, message: "is incorrect" }
  validates :name, presence: true, format: { with: /\A[a-zA-ZąćęłńóśźżĄĆĘŁŃÓŚŹŻ\s,\-]+\z/, message: "is incorrect" }
  validates :address, presence: true, format: { with: /\A[a-zA-ZąćęłńóśźżĄĆĘŁŃÓŚŹŻ\d\s,\-]+\z/, message: "is incorrect" }
end

app/controllers/transfers_controller.rb
class TransfersController < ApplicationController
    before_action :authenticate_user!

    def index
        # Paginacja dla przekazywanych przelewów
        @transfers_sent = current_user.transfers.paginate(page: params[:sent_page], per_page: 4)
    
        # Paginacja dla otrzymywanych przelewów
        @transfers_received = Transfer.where(receiver_account_number: current_user.account_no)
                                      .paginate(page: params[:received_page], per_page: 4)
      end
      

    def new
        @transfer = Transfer.new
    end

    def create
        @transfer = Transfer.new(transfer_params)

        if enough_balance? && @transfer.save
            
            if valid_receiver?
                transfer_money_to_receiver
            end 

            redirect_to root_path, alert: 'Transfer created successfully.'
        else
            flash.now[:alert] = 'Error creating transfer. Please fix the following issues:'
            render :new
        end
    end
    
      private
    
      def transfer_params
        params.require(:transfer).permit(:amount, :sender_account_number, :receiver_account_number,:user_id,:address,:name,:title)
      end

      def valid_receiver?
        receiver = User.find_by(account_no: @transfer.receiver_account_number)
        return receiver.present?
      end

      def transfer_money_to_receiver
        receiver = User.find_by(account_no: @transfer.receiver_account_number)
        receiver.money += @transfer.amount
        receiver.save
      end

      def enough_balance?
        if @transfer.amount.blank?
            @transfer.errors.add(:base, 'Amount cannot be blank')
            return false
        end

        user = User.find(transfer_params[:user_id])

        if user.money >= @transfer.amount
            user.money -= @transfer.amount
            user.save
            return true
        else
            @transfer.errors.add(:amount, 'Insufficient balance for the transfer')
        return false
    end

      end

end


 

app/views/transfers/index.html.erb
<main class="min-h-screen w-full bg-white text-gray-700" x-data="layout">
    <!-- header page -->
    <header class="flex w-full w-auto items-center justify-between bg-purple-blue-500 p-2 text-white">
        <!-- logo -->
        <div class="flex items-center space-x-2">
            <button type="button" class="text-3xl pt-1.5" @click="asideOpen = !asideOpen"><ion-icon name="menu-outline"></ion-icon></button>
            <div>SecurePay</div>
        </div>

        <!-- button profile -->
        <div>
            <%= link_to "/users/sign_out", method: :delete, class: "text-2xl h-9 w-9 overflow-hidden rounded-full" do %>
              <ion-icon name="log-out-outline"></ion-icon>
            <% end %>

            <div class="absolute right-2 mt-1 w-48 divide-y  rounded-md  bg-white"
                x-show="profileOpen" x-transition>
            </div>
        </div>
    </header>

    <div class="flex">
        <aside class="flex w-72 flex-col space-y-2 bg-white p-2" style="height: 90.5vh"
            x-show="asideOpen">
            <%= link_to "/", class: "flex items-center space-x-1 rounded-md px-2 py-3 hover:bg-gray-100 hover:text-blue-600" do %>
              <span class="text-2xl pt-1.5"><ion-icon name="home-outline"></ion-icon></span>
              <span>Home</span>
            <% end %>

            <%= link_to "/transfers", class: "flex items-center space-x-1 rounded-md px-2 py-3 hover:bg-gray-100 hover:text-blue-600" do %>
              <span class="text-2xl pt-1.5"><ion-icon name="card-outline"></ion-icon></span>
              <span>Payments</span>
            <% end %>

            <%= link_to "/my_account", class: "flex items-center space-x-1 rounded-md px-2 py-3 hover:bg-gray-100 hover:text-blue-600" do %>
              <span class="text-2xl pt-1.5"><ion-icon name="person-outline"></ion-icon></span>
              <span>My account</span>
            <% end %>
          
          <%= link_to "/users/edit", class: "flex items-center space-x-1 rounded-md px-2 py-3 hover:bg-gray-100 hover:text-blue-600" do %>
            <span class="text-2xl pt-1.5"><ion-icon name="settings-outline"></ion-icon></span>
            <span>Settings</span>
          <% end %>
        </aside>

        <!-- main content page -->
<div class="w-full h-auto min-h-screen bg-white border-l-2 border-dark-grey-900">
                
<div class="p-20 mx-auto">

<div class="pb-20">
  <%= link_to "New transfer", "/transfers/new", 
  class: "bg-purple-blue-500 w-36 px-6 py-5 font-bold leading-none text-white transition duration-300 ml-auto rounded-2xl hover:text-white hover:bg-purple-blue-600 focus:ring-4 focus:ring-purple-blue-100" %>
</div>

	<div class="relative overflow-x-auto shadow-md sm:rounded-lg">
  <h2 class="mb-3 font-bold">Sent transfers</h2>
			<table class="w-full text-sm text-left text-gray-500">
				<thead class="text-sm text-gray-900 bg-gray-100">
					<tr>
						<th scope="col" class="px-6 py-3">
							Title
						</th>
						<th scope="col" class="px-6 py-3">
							Amount
						</th>
						<th scope="col" class="px-6 py-3">
							Reciever name
						</th>
            <th scope="col" class="px-6 py-3">
							Reciever account
						</th>
            <th scope="col" class="px-6 py-3">
							Reciever address
						</th>
						<th scope="col" class="px-6 py-3">
							Date
						</th>
					</tr>
				</thead>
				<tbody>

        <% @transfers_sent.each do |transfer| %>
					<tr
						class="bg-white border-b hover:bg-gray-50">
						<th scope="row" class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap">
							<%= transfer.title %></p>
						</th>
						<td class="px-6 py-4 text-gray-900">
							<%= transfer.amount %></p>
						</td>
						<td class="px-6 py-4 text-gray-900 ">
							<%= transfer.name %>
						</td>
						<td class="px-6 py-4 text-gray-900">
							<%= transfer.receiver_account_number %></p>
						</td>
            <td class="px-6 py-4 text-gray-900">
							<%= transfer.address %>
						</td>
            <td class="px-6 py-4 text-gray-900">
							<%= transfer.updated_at %>
						</td>  
					</tr>
          <% end %>
				</tbody>
			</table>
		</div>

    <div class="text-gray-900 text-center mt-4">
    <%= will_paginate @transfers_sent, param_name: 'sent_page', previous_label: 'Previous', next_label: 'Next' %>
    </div>

    <div class="relative mt-16 overflow-x-auto shadow-md sm:rounded-lg">
    <h2 class="mb-3 font-bold">Received transfers</h2>
			<table class="w-full text-sm text-left text-gray-500">
				<thead class="text-sm text-gray-900 bg-gray-100">
					<tr>
						<th scope="col" class="px-6 py-3">
							Title
						</th>
						<th scope="col" class="px-6 py-3">
							Amount
						</th>
						<th scope="col" class="px-6 py-3">
							Reciever name
						</th>
            <th scope="col" class="px-6 py-3">
							Sender account
						</th>
            <th scope="col" class="px-6 py-3">
							My address
						</th>
						<th scope="col" class="px-6 py-3">
							Date
						</th>
					</tr>
				</thead>
				<tbody>

        <% @transfers_received.each do |transfer| %>
					<tr
						class="bg-white border-b hover:bg-gray-50">
						<th scope="row" class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap">
							<%= transfer.title %></p>
						</th>
						<td class="px-6 py-4 text-gray-900">
							<%= transfer.amount %></p>
						</td>
						<td class="px-6 py-4 text-gray-900 ">
							ME
						</td>
						<td class="px-6 py-4 text-gray-900">
							<%= transfer.sender_account_number %></p>
						</td>
            <td class="px-6 py-4 text-gray-900">
							<%= transfer.address %>
						</td>
            <td class="px-6 py-4 text-gray-900">
							<%= transfer.created_at %>
						</td>  
					</tr>
          <% end %>
				</tbody>
			</table>
		</div>
  
    <div class="text-gray-900 text-center mt-4">
    <%= will_paginate @transfers_received, param_name: 'received_page', previous_label: 'Previous', next_label: 'Next' %>
    </div>
  </div>




                </div>
        
    </div>
</main>

<script>
    document.addEventListener("alpine:init", () => {
        Alpine.data("layout", () => ({
            profileOpen: false,
            asideOpen: true,
        }));
    });
</script>

app/views/transfers/new.html.erb
<main class="min-h-screen w-full bg-white text-gray-700" x-data="layout">
    <!-- header page -->
    <header class="flex w-full items-center justify-between  bg-purple-blue-500 p-2 text-white">
        <!-- logo -->
        <div class="flex items-center space-x-2">
            <button type="button" class="text-3xl pt-1.5" @click="asideOpen = !asideOpen"><ion-icon name="menu-outline"></ion-icon></button>
            <div>SecurePay</div>
        </div>

        <!-- button profile -->
        <div>
            <%= link_to "/users/sign_out", method: :delete, class: "text-2xl h-9 w-9 overflow-hidden rounded-full" do %>
              <ion-icon name="log-out-outline"></ion-icon>
            <% end %>

            <div class="absolute right-2 mt-1 w-48 divide-y  rounded-md  bg-white"
                x-show="profileOpen" x-transition>
            </div>
        </div>
    </header>

    <div class="flex h-full my-auto">
        <aside class="flex w-72 flex-col space-y-2 bg-white p-2" style="height: 90.5vh"
            x-show="asideOpen">
            <%= link_to "/", class: "flex items-center space-x-1 rounded-md px-2 py-3 hover:bg-gray-100 hover:text-blue-600" do %>
              <span class="text-2xl pt-1.5"><ion-icon name="home-outline"></ion-icon></span>
              <span>Home</span>
            <% end %>

            <%= link_to "/transfers", class: "flex items-center space-x-1 rounded-md px-2 py-3 hover:bg-gray-100 hover:text-blue-600" do %>
              <span class="text-2xl pt-1.5"><ion-icon name="card-outline"></ion-icon></span>
              <span>Payments</span>
            <% end %>

            <%= link_to "/my_account", class: "flex items-center space-x-1 rounded-md px-2 py-3 hover:bg-gray-100 hover:text-blue-600" do %>
              <span class="text-2xl pt-1.5"><ion-icon name="person-outline"></ion-icon></span>
              <span>My account</span>
            <% end %>
          
          <%= link_to "/users/edit", class: "flex items-center space-x-1 rounded-md px-2 py-3 hover:bg-gray-100 hover:text-blue-600" do %>
            <span class="text-2xl pt-1.5"><ion-icon name="settings-outline"></ion-icon></span>
            <span>Settings</span>
          <% end %>
        </aside>

<!-- main content page -->
<div class="w-full p-4 bg-white border-l-2 border-dark-grey-900">

<div class="">    
    <div class="container flex flex-col mx-auto">
        <div class="flex justify-center w-full h-full my-auto xl:gap-14 lg:justify-normal md:gap-5 draggable">
            <div class="flex items-center justify-center w-full lg:p-12">
                <div class="flex items-center xl:p-10">
                  <div class="flex flex-col w-full h-full pb-6 text-center">


          <h3 class="mb-3 text-4xl font-bold text-dark-grey-900">Make a new trasfer</h3>
                        <p class="mb-7 text-grey-700">Fill in all fields</p>

              <% if @transfer.errors.any? %>
                <div class="bg-red-100 text-red-700 p-2 mb-7 rounded">
                  <strong>Error:</strong>
                  <ul>
                    <% @transfer.errors.full_messages.each do |message| %>
                      <li><%= message %></li>
                    <% end %>
                  </ul>
                </div>
              <% end %>

<%= form_with(model: @transfer, url: transfers_path, method: :post) do |form| %>
  <div class="field flex flex-col">
    <%= form.label :title, class: "mb-2 text-xl text-start text-grey-900" %>
    <%= form.text_field :title, class: "flex items-center w-full px-5 py-4 mr-2 text-sm font-medium outline-none focus:bg-gray-200 mb-7 bg-gray-100 text-dark-grey-900 rounded-2xl", maxlength: 45 %>
  </div>

  <div class="field flex flex-col">
    <%= form.label :amount, class: "mb-2 text-xl text-start text-grey-900" %>
    <%= form.text_field :amount, class: "flex items-center w-full px-5 py-4 mr-2 text-sm font-medium outline-none focus:bg-gray-200 mb-7 bg-gray-100 text-dark-grey-900 rounded-2xl" %>
  </div>

  <div class="field flex flex-col">
    <%= form.label :receiver_account_number, class: "mb-2 text-xl text-start text-grey-900" %>
    <%= form.text_field :receiver_account_number, class: "flex items-center w-full px-5 py-4 mr-2 text-sm font-medium outline-none focus:bg-gray-200 mb-7 bg-gray-100 text-dark-grey-900 rounded-2xl", maxlength: 26 %>
  </div>

  <div class="field flex flex-col">
    <%= form.label :name, class: "mb-2 text-xl text-start text-grey-900" %>
    <%= form.text_field :name, class: "flex items-center w-full px-5 py-4 mr-2 text-sm font-medium outline-none focus:bg-gray-200 mb-7 bg-gray-100 text-dark-grey-900 rounded-2xl", maxlength: 45 %>
  </div>

  <div class="field flex flex-col">
    <%= form.label :address, class: "mb-2 text-xl text-start text-grey-900" %>
    <%= form.text_field :address, class: "flex items-center w-full px-5 py-4 mr-2 text-sm font-medium outline-none focus:bg-gray-200 mb-7 bg-gray-100 text-dark-grey-900 rounded-2xl", maxlength: 50 %>
  </div>

  <div class="field flex flex-col">
    <%= form.label :sender_account_number, class: "mb-2 text-xl text-start text-grey-900" %>
    <%= form.text_field :sender_account_number,
                    readonly: true,
                    value: current_user.account_no, class: "flex items-center w-full px-5 py-4 mr-2 text-sm font-medium outline-none focus:bg-gray-200 mb-7 bg-gray-100 text-dark-grey-900 rounded-2xl" %>
  </div>

              <%= form.hidden_field :user_id, value: current_user.id %>


              <div>
                <%= form.submit "Create Transfer" %>
              </div>
            <% end %>
                
                  </div>  
                </div>
            </div>
        </div>
    </div>
</div>



                </div>
      <!-- main content page -->           


    </div>
</main>

<script>
    document.addEventListener("alpine:init", () => {
        Alpine.data("layout", () => ({
            profileOpen: false,
            asideOpen: true,
        }));
    });
</script>